project:
  type: website
  output-dir: docs
  resources: 
    - CNAME

website:
  page-navigation: true
  title: "STA 313"
  description: "Homepage for STA 313 - Advanced Data Visualization at Duke University, Spring 2026."
  #site-url: "https://vizdata.org/"

  repo-url: https://github.com/vizdata-s26/vizdata-s26/
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    image: "images/twitter-card.png"

  sidebar:
    background: "#f1de67" # Arylide Yellow
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/vizdata-s26
        text: "GitHub organization"
      - icon: code-square
        href: https://rstudio.stat.duke.edu
        text: "Posit Workbench"
      - icon: life-preserver
        text: Support
        menu:
          - icon: person-raised-hand
            text: Office hours
            href: https://docs.google.com/spreadsheets/d/1rVx9uZVNcrG_nUSDo7iol5VEeGcHURASVtBpwZjz5bc/edit?usp=sharing
          - icon: people-fill
            text: Ed Discussion
            href: https://edstem.org/us/courses/71474/discussion
      - icon: file-check-fill
        text: "Canvas"
        menu:
          - icon: megaphone-fill
            text: Announcements
            url: https://canvas.duke.edu/courses/71474/announcements
          - icon: alphabet-uppercase
            text: Gradebook
            url: https://canvas.duke.edu/courses/71474/gradebook

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Computing"
        contents:
          - href: computing/computing-setup.qmd
            text: Setup
          - href: computing/computing-troubleshooting.qmd
            text: Troubleshooting
          - href: computing/computing-cheatsheets.qmd
            text: Cheatsheets
      - ae.qmd
      - hw.qmd
      - section: "Mini-projects"
        contents:
          - href: mini-projects/mini-project-1.qmd
          - href: mini-projects/mini-project-2.qmd
          - href: mini-projects/mini-project-tips-resources.qmd
            text: Tips + resources
      - section: "Projects"
        contents:
          - href: projects/project-1.qmd
          - href: projects/project-2.qmd
          - href: projects/project-tips-resources.qmd
            text: Tips + resources
      - section: "Student work"
        contents:
          - href: student-work/thank-you.qmd
            text: Thank you cards
          - href: student-work/ugly-plot.qmd
            text: Ugly plots
          - href: student-work/mini-project-1.qmd
            text: Mini-project 1
          - href: student-work/mini-project-2.qmd
            text: Mini-project 2
          - href: student-work/project-1.qmd
            text: Project 1
          - href: student-work/project-2.qmd
            text: Project 2
          
  page-footer:
    right: "This page is built with ðŸ’› and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Mine Ã‡etinkaya-Rundel"
    background: "#f1de67" # Arylide Yellow
    
format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [cosmo, style/sta313.scss]
      dark: [cosmo, style/sta313.scss, style/dark.scss]
    linkcolor: "#866fa3" # Glossy Grape
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    highlight-style: 
      light: a11y
      dark: a11y-dark
    code-link: true

editor: source

execute: 
  freeze: auto
